"""
Agent 2: Code Generator
Responsible for generating runnable code based on ILR and interface constraints, using language model 1
"""

import json
from typing import Dict, Any, Optional
from pathlib import Path
from utils.vision_api_client import VisionAPIClient
from utils.code_utils import extract_code
from utils.intermediate_representation import (
    get_intermediate_representation_display_name,
    normalize_intermediate_representation_type,
)
from agents.self_planning_prompt_utils import insert_before


class CodeGenerator:
    """Code Generator"""

    def __init__(self, config_dict: Dict[str, Any] = None, output_dir: str = None,
                 prompt_variant: str = "default",
                 include_problem_text_description: bool = True):
        """
        Initialize the code generator

        Args:
            config_dict: Config dictionary, format consistent with src
            output_dir: Output directory path
            prompt_variant: Prompt variant
            include_problem_text_description: Whether to include problem text description in code generation prompt
        """
        # Use language model
        self.language_client = VisionAPIClient(config_dict=config_dict)
        self.output_dir = output_dir or str(Path(__file__).parent.parent.parent / "output")
        self.prompt_variant = (prompt_variant or "default").strip().lower()
        self.include_problem_text_description = include_problem_text_description

    def _use_self_planning(self) -> bool:
        return self.prompt_variant == "self_planning"

    def _apply_self_planning(self, prompt: str, marker: str, block: str) -> str:
        if not self._use_self_planning():
            return prompt
        return insert_before(prompt, marker, block)

    def generate_code(self, ilr: str, problem_info: Dict[str, Any],
                      representation_type: str = "ilr") -> tuple:
        """
        Generate runnable code based on ILR and interface constraints

        Args:
            ilr: Intermediate representation generated by agent1
            problem_info: Problem info, including starter_code, test cases, description, etc.
            representation_type: Intermediate representation type (ilr/text)

        Returns:
            (Generated code, token usage info)
        """
        try:
            # Build prompt
            prompt = self._build_code_generation_prompt(
                ilr,
                problem_info,
                representation_type=representation_type,
            )

            # Call language model API
            generated_code, usage = self.language_client.generate_text(prompt)

            # Clean generated code (remove possible markdown markers)
            cleaned_code = self._clean_generated_code(generated_code)

            # Fix function name to ensure consistency with starter_code
            cleaned_code = self._fix_function_name(cleaned_code, problem_info)

            return cleaned_code, usage

        except Exception as e:
            print(f"Code generation failed: {e}")
            return self._generate_fallback_code(problem_info), {}

    def generate_code_with_reflection(self, ilr: str, problem_info: Dict[str, Any],
                                      original_code: str, analysis: str,
                                      representation_type: str = "ilr") -> tuple:
        """
        Regenerate code based on reflection

        Args:
            ilr: Intermediate representation (may be corrected, or original)
            problem_info: Problem info
            original_code: Original erroneous code
            analysis: Error analysis and improvement suggestions
            representation_type: Intermediate representation type (ilr/text)

        Returns:
            (Generated code, token usage info)
        """
        try:
            # Build prompt with reflection
            prompt = self._build_code_generation_prompt_with_reflection(
                ilr,
                problem_info,
                original_code,
                analysis,
                representation_type=representation_type,
            )

            # Call language model API
            generated_code, usage = self.language_client.generate_text(prompt)

            # Clean generated code
            cleaned_code = self._clean_generated_code(generated_code)

            # Fix function name
            cleaned_code = self._fix_function_name(cleaned_code, problem_info)

            return cleaned_code, usage

        except Exception as e:
            print(f"Reflection-based code generation failed: {e}")
            return self._generate_fallback_code(problem_info), {}

    def generate_code_from_code_reflection(self, problem_info: Dict[str, Any],
                                           original_code: str, analysis: str,
                                           image_path: Optional[str] = None) -> tuple:
        """
        Code reflection ablation: Does not rely on any intermediate representation, directly revises code based on interface constraints and failed code.

        Args:
            problem_info: Problem info
            original_code: Original erroneous code
            analysis: Code problem analysis

        Returns:
            (Generated code, token usage info)
        """
        try:
            prompt = self._build_code_only_reflection_prompt(
                problem_info=problem_info,
                original_code=original_code,
                analysis=analysis,
            )

            try:
                if image_path:
                    response = self.language_client.call_api(
                        prompt=prompt,
                        image_path=image_path
                    )
                    generated_code = response.get("content", "")
                    usage = response.get("usage", {})
                else:
                    generated_code, usage = self.language_client.generate_text(prompt)
            except Exception as exc:
                if image_path:
                    print(f"Code revision with image failed, falling back to text-only generation: {exc}")
                    generated_code, usage = self.language_client.generate_text(prompt)
                else:
                    raise
            cleaned_code = self._clean_generated_code(generated_code)
            cleaned_code = self._fix_function_name(cleaned_code, problem_info)
            return cleaned_code, usage
        except Exception as e:
            print(f"Code ablation reflection generation failed: {e}")
            return self._generate_fallback_code(problem_info), {}

    def _fix_function_name(self, code: str, problem_info: Dict[str, Any]) -> str:
        """
        Fix function name to ensure consistency with starter_code

        Args:
            code: Generated code
            problem_info: Problem info

        Returns:
            Corrected code
        """
        import re

        # Extract function name from starter_code
        starter_code = problem_info.get('starter_code', '')
        func_name_match = re.search(r'def\s+(\w+)\s*\(', starter_code)
        if not func_name_match:
            print(f"Warning: Cannot extract function name from starter_code: {starter_code}")
            return code

        correct_function_name = func_name_match.group(1)

        # Extract function name from generated code
        generated_func_match = re.search(r'def\s+(\w+)\s*\(', code)
        if not generated_func_match:
            print(f"Warning: Cannot extract function name from generated code")
            return code

        generated_function_name = generated_func_match.group(1)

        print(f"Function name check: correct function name={correct_function_name}, generated function name={generated_function_name}")

        # If function names are inconsistent, replace
        if generated_function_name != correct_function_name:
            # Replace function name in function definition
            code = re.sub(
                r'\bdef\s+' + re.escape(generated_function_name) + r'\s*\(',
                f'def {correct_function_name}(',
                code
            )
            print(f"Fixed function name: {generated_function_name} -> {correct_function_name}")
        else:
            print(f"Function names are consistent, no fix needed")

        return code

    def _build_code_generation_prompt(self, ilr: str, problem_info: Dict[str, Any],
                                      representation_type: str = "ilr") -> str:
        """Build code generation prompt (generates complete function definition)."""
        representation_type = normalize_intermediate_representation_type(representation_type)
        starter_code = problem_info.get('starter_code', '')
        function_name = problem_info.get('entry_point', 'solution')
        # Compatible with both field names: description and text_description
        description = ''
        if self.include_problem_text_description:
            description = problem_info.get('description', '') or problem_info.get('text_description', '')

        # The external parameterized tester adapts stdin; generated code keeps solve(arg0, ...) signature.
        lcb_mode = problem_info.get("lcb_mode", "")
        if not lcb_mode and starter_code.lstrip().startswith("def solve(") and "class Solution" not in starter_code:
            lcb_mode = "stdio"
        interface_note = ""
        if lcb_mode == "stdio":
            interface_note = """
## LCB Standard-Input Adapter
- Keep the exact parameterized solve(arg0, arg1, ...) signature above.
- The evaluator supplies parsed stdin values as function arguments.
- Do not call solve() at module import time and do not add a standalone input loop.
- Return the answer from solve; the evaluator handles stdin/stdout adaptation.
"""
        # Extract function signature (from starter_code)
        import re
        function_signature = starter_code
        if not function_signature or ':' not in function_signature:
            # If there is no valid starter_code, use default function signature
            function_signature = f"def {function_name}():"

        # Build problem description section (controlled by include_problem_text_description)
        description_section = ""
        if description:
            description_section = f"""
## Problem Description:
{description}
"""

        if representation_type == "text":
            return self._build_text_code_generation_prompt(
                ilr,
                function_signature,
                description_section=description_section,
            )

        # Enhanced prompt, including ILR structure explanation and conversion rules
        prompt = f"""# Task: Convert ILR to Python Code

You are given an Intermediate Logic Representation (ILR) extracted from a flowchart. Your task is to convert it into a working Python function.

## ILR Structure Explanation

The ILR is a JSON object with these components:
- `problem_id`: Identifier for the problem
- `nodes`: List of flowchart nodes, each containing:
  - `id`: Unique integer identifier
  - `type`: One of ["start", "process", "decision", "end"]
  - `label`: Human-readable description of the node
  - `next`: ID of the next node (for start/process nodes)
  - `action`: Python statement to execute (for process nodes), uses `ctx['var']` syntax
  - `logic`: Boolean expression (for decision nodes), uses `ctx['var']` syntax
  - `true_next`/`false_next`: Branch targets (for decision nodes)
  - `output`: Return expression (for end nodes)

## Conversion Rules

1. **Variable Mapping**:
   - `ctx['variable_name']` in ILR → use as local variable `variable_name` in your code
   - Function parameters should be used directly (not from ctx)

2. **Node Type Mapping**:
   - `start` node: Entry point, follow `next` pointer
   - `process` node: Execute `action` as a statement, then follow `next`
   - `decision` node: Convert to `if/elif/else` or `while` loop based on control flow
   - `end` node: Convert `output` to `return` statement

3. **Control Flow Detection**:
   - If a decision node's true/false branch eventually loops back to itself → use `while` loop
   - If branches don't loop back → use `if/else` statement
   - Trace the `next`, `true_next`, `false_next` pointers to understand the flow

4. **Loop Pattern Recognition**:
   - Pattern: decision → process → back to same decision = `while` loop
   - The decision's `logic` becomes the while condition
   - Process nodes in the loop become the loop body
{description_section}
{interface_note}
## ILR to Convert:
```json
{ilr}
```

## Required Function Signature (MUST use exactly):
```python
{function_signature}
```

## Requirements:
1. Use the EXACT function signature provided above
2. Map `ctx['param']` references to function parameters where applicable
3. Implement proper control flow (if/else, while loops) based on the ILR structure
4. Return the correct value as specified in the `end` node's `output` field
5. Handle edge cases appropriately
6. Import any necessary packages at the top

## Output Format:
Provide ONLY the complete Python function between ```python and ```.
Do NOT include any explanation, just the code.

```python
{function_signature}
    # Your implementation here
```"""
        return self._apply_self_planning(
            prompt,
            "## Output Format:",
            "## Self-Planning (internal)\n- Outline control flow and loop structure\n- Map ctx variables to locals and parameters\n- Identify edge cases implied by ILR\nDo NOT output the plan."
        )

    def _build_text_code_generation_prompt(self, text_ir: str, function_signature: str,
                                           description_section: str = "") -> str:
        """Build code generation prompt based on textual intermediate representation."""
        prompt = f"""# Task: Convert Textual Intermediate Representation to Python Code

You are given a plain-text intermediate representation extracted from a flowchart.
This is an ablation setting where Agent 1 does NOT provide ILR JSON.
Your task is to convert the textual intermediate representation into a correct Python function.

## Text IR Interpretation Rules

1. Treat the text as the authoritative algorithm description.
2. The text may be free-form natural language (not a fixed template).
3. Infer control flow from explicit cues such as IF, ELSE, WHILE, FOR EACH, RETURN.
4. Preserve parameter order exactly as described in the required function signature.
5. Respect all explicitly described variable initialization steps.
6. If helper functions are described, implement them as Python helper functions.
7. If the text is ambiguous, resolve it conservatively using only the flowchart-derived text IR and starter code.
8. Do not invent algorithm steps that are unsupported by the text IR.
{description_section}
## Text IR to Convert:
{text_ir}

## Required Function Signature (MUST use exactly):
```python
{function_signature}
```

        ## Requirements:
1. Use the EXACT function signature provided above
2. Convert the textual control flow into valid Python control flow
3. Keep variable names and helper function intent consistent with the text IR
4. Return the correct value described in the text IR
5. Handle edge cases appropriately
6. Import any necessary packages at the top

## Output Format:
Provide ONLY the complete Python function between ```python and ```.
Do NOT include any explanation, just the code.

```python
{function_signature}
    # Your implementation here
```"""
        return self._apply_self_planning(
            prompt,
            "## Output Format:",
            "## Self-Planning (internal)\n- Outline control flow and helper functions from Text IR\n- Map parameters in exact signature order\n- Identify edge cases implied by Text IR\nDo NOT output the plan."
        )

    def _build_code_generation_prompt_with_reflection(self, ilr: str, problem_info: Dict[str, Any],
                                                      original_code: str, analysis: str,
                                                      representation_type: str = "ilr") -> str:
        """Build code generation prompt with reflection (following the structure of the normal generation prompt)."""
        representation_type = normalize_intermediate_representation_type(representation_type)

        # Use the same base prompt as normal generation
        base_prompt = self._build_code_generation_prompt(
            ilr,
            problem_info,
            representation_type=representation_type,
        )
        display_name = get_intermediate_representation_display_name(representation_type)

        # Add reflection section
        reflection_section = f"""

## Previous Attempt and Reflection

We previously generated code that failed test cases.

### Previous Code (INCORRECT):
```python
{original_code}
```

### Issues Identified:
{analysis}

### Task:
Before generating the corrected code, briefly trace through the previous code's execution for a failing test case to pinpoint where the logic goes wrong. Keep this reasoning concise (3-5 sentences max), then generate the CORRECTED Python code that addresses the above issues. Follow all the conversion rules and requirements above.
"""

        if representation_type == "text":
            reflection_section = reflection_section.replace(
                "Follow all the conversion rules and requirements above.",
                f"Follow the {display_name}-to-code conversion rules and requirements above."
            )

        # Insert reflection section before "## Output Format:"
        parts = base_prompt.split("## Output Format:")
        if len(parts) == 2:
            return parts[0] + reflection_section + "\n## Output Format:" + parts[1]
        else:
            return base_prompt + reflection_section

    def _build_code_only_reflection_prompt(self, problem_info: Dict[str, Any],
                                           original_code: str, analysis: str) -> str:
        """Build code revision prompt without ILR dependency."""
        starter_code = problem_info.get('starter_code', '')
        function_name = problem_info.get('entry_point', 'solution')
        # Compatible with both field names: description and text_description
        description = ''
        if self.include_problem_text_description:
            description = problem_info.get('description', '') or problem_info.get('text_description', '')
        function_signature = starter_code
        if not function_signature or ':' not in function_signature:
            function_signature = f"def {function_name}():"

        # Build problem description section (controlled by include_problem_text_description)
        description_section = ""
        if description:
            description_section = f"""
## Problem Description:
{description}
"""

        prompt = f"""# Task: Fix Python Code Based on Reflection

You are given a failed Python solution and a code-review style reflection describing its bugs.
This is a code-only ablation setting: there is NO ILR and you must only reason about code problems.
You will also receive the original flowchart image as visual reference when available.
{description_section}
## Required Function Signature (MUST use exactly):
```python
{function_signature}
```

## Previous Code (INCORRECT):
```python
{original_code}
```

## Reflection:
{analysis}

## Requirements:
1. Use the EXACT function signature provided above
2. Fix the code according to the reflection
3. Preserve the intended algorithm unless the reflection shows it is wrong
4. Handle the failing edge cases and boundary conditions
5. Import any necessary packages at the top
6. Output only the corrected code, with no explanation
7. Do NOT repeat or paraphrase the reflection
8. Do NOT add comments unless they are required for correctness
9. Do NOT rewrite the whole algorithm unless the reflection indicates the algorithm itself is wrong
10. Preserve as much of the previous code structure as possible while fixing the bugs
11. Ignore markdown fence issues from previous outputs; focus on repairing the executable Python code itself

## Output Format:
Provide ONLY the complete Python function between ```python and ```.

```python
{function_signature}
    # Your corrected implementation here
```"""
        return self._apply_self_planning(
            prompt,
            "## Output Format:",
            "## Self-Planning (internal)\n- Locate the first incorrect decision or update\n- List minimal code changes needed\n- Verify signature and return value\nDo NOT output the plan."
        )

    
    def _format_test_cases(self, test_cases: list) -> str:
        """Format test cases as string"""
        if not test_cases:
            return "No test cases provided"
        
        formatted = []
        for i, case in enumerate(test_cases, 1):
            input_str = case.get('input', '')
            output_str = case.get('output', '')
            explanation = case.get('explanation', '')
            
            case_str = f"Test Case {i}:"
            if input_str:
                case_str += f"\nInput: {input_str}"
            if output_str:
                case_str += f"\nOutput: {output_str}"
            if explanation:
                case_str += f"\nExplanation: {explanation}"
            
            formatted.append(case_str)
        
        return '\n\n'.join(formatted)
    
    def _clean_generated_code(self, generated_code: str) -> str:
        """Clean generated code, extract code block content (consistent with src)"""
        # Use extract_code function (completely consistent with src)
        return extract_code(generated_code)
    
    def _generate_fallback_code(self, problem_info: Dict[str, Any]) -> str:
        """Generate fallback code (when API call fails)"""
        starter_code = problem_info.get('starter_code', '')
        
        # Return starter code directly only for solve(...) standard-input interfaces.
        import re
        if starter_code and re.match(r"def\s+solve\s*\(", starter_code.lstrip()):
            return starter_code
        if starter_code and 'class Solution:' in starter_code:
            # Extract method signature
            import re
            method_pattern = r'def (\w+)\(self.*?\):'
            method_match = re.search(method_pattern, starter_code)
            if method_match:
                method_name = method_match.group(1)
                fallback_code = f'''class Solution:
    def {method_name}(self):
        # TODO: Implement based on the flowchart-derived intermediate representation.
        pass
'''
            else:
                fallback_code = starter_code
        else:
            fallback_code = '''class Solution:
    def solution(self):
        """
        Fallback implementation
        """
        pass
'''
        return fallback_code
    
    def validate_code_syntax(self, code: str) -> bool:
        """Validate whether code syntax is correct"""
        try:
            # Try to compile the code
            compile(code, '<string>', 'exec')
            return True
        except SyntaxError as e:
            print(f"Code syntax error: {e}")
            return False
        except Exception as e:
            print(f"Error during code validation: {e}")
            return False


def test_code_generator():
    """Test the code generator"""
    generator = CodeGenerator()

    # Test data
    test_ilr = '''{
  "problem_id": "test_001",
  "nodes": [
    {
      "id": 1,
      "type": "start",
      "label": "Start",
      "next": 2
    },
    {
      "id": 2,
      "type": "process",
      "label": "Initialize count",
      "action": "ctx['count'] = 0",
      "next": 3
    },
    {
      "id": 3,
      "type": "decision",
      "label": "For each character",
      "logic": "len(ctx['chars']) > 0",
      "true_next": 4,
      "false_next": 6
    },
    {
      "id": 4,
      "type": "decision",
      "label": "Is vowel?",
      "logic": "ctx['char'] in ['a', 'e', 'i', 'o', 'u']",
      "true_next": 5,
      "false_next": 3
    },
    {
      "id": 5,
      "type": "process",
      "label": "Increment count",
      "action": "ctx['count'] += 1",
      "next": 3
    },
    {
      "id": 6,
      "type": "end",
      "label": "Return count",
      "output": "ctx['count']"
    }
  ]
}'''

    test_problem_info = {
        'title': 'Count Vowels',
        'starter_code': 'def count_vowels(word):',
        'test_cases': [
            {'input': '"hello"', 'output': '2', 'explanation': 'e and o are vowels'},
            {'input': '"world"', 'output': '1', 'explanation': 'o is a vowel'}
        ]
    }

    print("=== Testing Code Generator ===")

    # Test syntax validation
    test_code = "def test(): return 1"
    print(f"Syntax validation test: {generator.validate_code_syntax(test_code)}")

    # Test code generation
    print("\nGenerating code...")
    generated_code = generator.generate_code(test_ilr, test_problem_info)

    print("Generated code:")
    print(generated_code)

    # Validate generated code syntax
    if generator.validate_code_syntax(generated_code):
        print("\nGenerated code syntax is correct")
    else:
        print("\nGenerated code has syntax errors")


if __name__ == "__main__":
    test_code_generator()
